# Generated by Django 5.2.4 on 2025-08-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Agenda de cuidados', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_establecimiento', models.CharField(choices=[('veterinaria', 'Veterinaria'), ('tienda_mascotas', 'Tienda de Mascotas'), ('peluqueria_canina', 'Peluquería Canina'), ('hotel_mascotas', 'Hotel de Mascotas'), ('parque', 'Parque para Mascotas'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.URLField(blank=True, max_length=500, null=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('vacuna', 'Vacuna'), ('veterinario', 'Visita Veterinario'), ('desparasitacion', 'Desparasitación'), ('peluqueria', 'Peluquería'), ('revision', 'Revisión General'), ('cuidado', 'Cuidado Especial'), ('otro', 'Otro')], max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_evento', models.DateTimeField()),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas_completado', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.agenda')),
            ],
            options={
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='ForoPyR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('es_mejor_respuesta', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.foropyr')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cita', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparacitacion', 'Desparasitación'), ('operacion', 'Operación'), ('revision', 'Revisión General'), ('emergencia', 'Emergencia'), ('otro', 'Otro')], max_length=20)),
                ('fecha_cita', models.DateTimeField()),
                ('peso', models.CharField(max_length=20)),
                ('caso', models.TextField()),
                ('proxima_cita', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='api.mascota')),
            ],
            options={
                'ordering': ['-fecha_cita'],
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='api.mascota'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(choices=[('normal', 'Normal'), ('organizacion', 'Organización'), ('veterinario', 'Veterinario')], default='normal', max_length=20)),
                ('cuenta_activa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_publicacion', models.CharField(choices=[('general', 'General'), ('adopcion', 'Adopción'), ('mascota_perdida', 'Mascota Perdida'), ('otro', 'Otro')], default='general', max_length=20)),
                ('categorias', models.ManyToManyField(blank=True, related_name='publicaciones', to='api.categoria')),
                ('mascotas_etiquetadas', models.ManyToManyField(blank=True, related_name='publicaciones_etiquetadas', to='api.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('solicitud', 'Solicitud Enviada'), ('revisando', 'En Revisión'), ('aceptada', 'Solicitud Aceptada'), ('rechazada', 'Solicitud Rechazada'), ('completada', 'Adopción Completada'), ('cancelada', 'Proceso Cancelado')], default='solicitud', max_length=20)),
                ('motivo_adopcion', models.TextField()),
                ('experiencia_mascotas', models.TextField(blank=True, null=True)),
                ('tiempo_disponible', models.CharField(blank=True, max_length=100, null=True)),
                ('vivienda_adecuada', models.BooleanField(default=False)),
                ('otros_mascotas', models.BooleanField(default=False)),
                ('descripcion_otros_mascotas', models.TextField(blank=True, null=True)),
                ('telefono_solicitante', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_solicitante', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('comentarios_propietario', models.TextField(blank=True, null=True)),
                ('comentarios_solicitante', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_adopcion', to='api.mascota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_en_adopcion', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adopcion', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_adopcion', to='api.publicacion')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MascotaPerdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas-perdidas/')),
                ('fecha_perdida', models.DateTimeField()),
                ('lugar_perdida', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('perdida', 'Perdida'), ('encontrada', 'Encontrada'), ('devuelta', 'Devuelta a su dueño')], default='perdida', max_length=20)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion_aproximada', models.TextField(blank=True, null=True)),
                ('caracteristicas_especiales', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_encontrada', models.DateTimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_perdida', to='api.mascota')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_perdidas', to='api.publicacion')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_oculto', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('gif', 'GIF'), ('otro', 'Otro')], default='imagen', max_length=10)),
                ('ruta_archivo', models.FileField(upload_to='publicaciones/archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='api.publicacion')),
            ],
            options={
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancion', models.CharField(choices=[('advertencia', 'Advertencia'), ('suspension_temporal', 'Suspensión Temporal'), ('suspension_permanente', 'Suspensión Permanente'), ('baneo', 'Baneo de la Plataforma')], max_length=30)),
                ('motivo', models.TextField()),
                ('fecha_sancion', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(blank=True, help_text='Si la suspensión es temporal, indicar hasta cuándo.', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('moderador', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_sancionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reaccion', models.CharField(choices=[('me_gusta', 'Me gusta'), ('me_encanta', 'Me encanta'), ('me_divierte', 'Me divierte'), ('me_asombra', 'Me asombra'), ('me_entristece', 'Me entristece')], default='me_gusta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='api.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_dadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En Revisión'), ('resuelto', 'Resuelto'), ('desestimado', 'Desestimado')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_moderador', models.TextField(blank=True, null=True)),
                ('moderador_asignado', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL)),
                ('publicacion_reportada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='api.publicacion')),
                ('usuario_reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reporte'],
                'unique_together': {('publicacion_reportada', 'usuario_reportante')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')])),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('establecimiento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='VotoForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_upvote', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entrada_foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='api.foropyr')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'entrada_foro')},
            },
        ),
    ]
