# Generated by Django 5.2.3 on 2025-07-31 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agenda_categoria_remove_publicacion_comentarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancion', models.CharField(choices=[('advertencia', 'Advertencia'), ('suspension_temporal', 'Suspensión Temporal'), ('suspension_permanente', 'Suspensión Permanente'), ('baneo', 'Baneo de la Plataforma')], max_length=30)),
                ('motivo', models.TextField()),
                ('fecha_sancion', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(blank=True, help_text='Si la suspensión es temporal, indicar hasta cuándo.', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('moderador', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_sancionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
