# Generated by Django 5.2.3 on 2025-07-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_establecimiento_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotaperdida',
            name='recompensa',
        ),
    ]
