# Generated by Django 5.2.4 on 2025-08-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mascotaperdida_recompensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='foto_usuario',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='mascotas_etiquetadas',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='tipo_publicacion',
        ),
    ]
