# Generated by Django 5.2.3 on 2025-08-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mascotaperdida_recompensa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopublicacion',
            name='ruta_archivo',
            field=models.FileField(upload_to='publicaciones/archivos/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='mascotaperdida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas-perdidas/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/usuarios/'),
        ),
    ]
