# Generated by Django 5.2.3 on 2025-08-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_archivopublicacion_ruta_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='foto_usuario',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='archivo_publicacion',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/usuarios/', verbose_name='Archivo de publicación'),
        ),
    ]
