# Generated by Django 5.2.3 on 2025-08-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_publicacion_foto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='archivo_publicacion',
        ),
    ]
