# Generated by Django 5.2.4 on 2025-08-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_publicacion_archivo_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cita', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparacitacion', 'Desparasitación'), ('operacion', 'Operación'), ('revision', 'Revisión General'), ('emergencia', 'Emergencia'), ('otro', 'Otro')], max_length=20)),
                ('fecha_cita', models.DateTimeField()),
                ('peso', models.CharField(max_length=20)),
                ('caso', models.TextField()),
                ('proxima_cita', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='api.mascota')),
            ],
            options={
                'ordering': ['-fecha_cita'],
            },
        ),
    ]
